---
server:
  port: 9120
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: Space_500862
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
